"""003_add_vehicle_detection

Revision ID: 5a11488c5fba
Revises: ed5ec8d9817d
Create Date: 2026-07-29 13:08:02.232795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a11488c5fba'
down_revision: Union[str, Sequence[str], None] = 'ed5ec8d9817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('plate_text', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_valid_plate', sa.Boolean(), nullable=False),
    sa.Column('upload_type', sa.String(length=10), nullable=False),
    sa.Column('uploaded_file_path', sa.String(length=500), nullable=False),
    sa.Column('cropped_vehicle_path', sa.String(length=500), nullable=True),
    sa.Column('cropped_plate_path', sa.String(length=500), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('detection_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ocr_raw_text', sa.String(length=50), nullable=True),
    sa.Column('detection_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vehicle_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_detections_plate_text'), 'vehicle_detections', ['plate_text'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_vehicle_id'), 'vehicle_detections', ['vehicle_id'], unique=False)
    op.add_column('vehicles', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicles', sa.Column('visit_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('vehicles', sa.Column('detection_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('vehicles', sa.Column('last_ocr_confidence', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('cropped_vehicle_image_path', sa.String(length=500), nullable=True))
    op.add_column('vehicles', sa.Column('cropped_plate_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'cropped_plate_image_path')
    op.drop_column('vehicles', 'cropped_vehicle_image_path')
    op.drop_column('vehicles', 'last_ocr_confidence')
    op.drop_column('vehicles', 'detection_count')
    op.drop_column('vehicles', 'visit_count')
    op.drop_column('vehicles', 'last_seen_at')
    op.drop_column('vehicles', 'first_seen_at')
    op.drop_index(op.f('ix_vehicle_detections_vehicle_id'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_plate_text'), table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    # ### end Alembic commands ###
