"""004_add_validation_metrics

Revision ID: 96a38ea6bfac
Revises: 5a11488c5fba
Create Date: 2026-07-29 21:34:02.846348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a38ea6bfac'
down_revision: Union[str, Sequence[str], None] = '5a11488c5fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_detections', sa.Column('corrected_plate', sa.String(length=20), nullable=True))
    op.add_column('vehicle_detections', sa.Column('vehicle_type_detected', sa.String(length=50), nullable=True))
    op.add_column('vehicle_detections', sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('vehicle_detections', sa.Column('pipeline_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('vehicle_detections', sa.Column('fusion_method', sa.String(length=30), nullable=True))
    op.add_column('vehicle_detections', sa.Column('character_consistency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_detections', 'character_consistency')
    op.drop_column('vehicle_detections', 'fusion_method')
    op.drop_column('vehicle_detections', 'pipeline_metrics')
    op.drop_column('vehicle_detections', 'validation_details')
    op.drop_column('vehicle_detections', 'vehicle_type_detected')
    op.drop_column('vehicle_detections', 'corrected_plate')
    # ### end Alembic commands ###
